language: python
python:
  - "3.7"

services:
  - xvfb

sudo: true

#cache: pip

#on_success: never
#on_failure: change

git:
  submodules: false

addons:
  apt:
    packages:
      - dpkg-dev 
      - build-essential 
      - python-dev 
      - libjpeg-dev 
      - libtiff5-dev 
      - libsdl1.2-dev 
      - libgstreamer-plugins-base0.10-dev 
      - libnotify-dev 
      - freeglut3 
      - freeglut3-dev 
      - libsm-dev 
      - libgtk-3-dev 
      - libpng16-16
      - libwebkitgtk-3.0-dev 
      - libgstreamer-plugins-base1.0-dev
      - at-spi2-core

 # command to install dependencies
install:
  - travis_wait 50 pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython
  - travis_wait 50 python setup.py install
  - pip install PyPubSub pyyaml ruamel.yaml matplotlib

# command to run
script: travis_wait 20 python devsimpy.py examples/model0/model0.dsp 10 start quit